export type PairWord = {
  words: [string, string];
  used: boolean;
};

export const pairWords: PairWord[] = [
  { words: ['ร้อน', 'เย็น'], used: false },
  { words: ['เร็ว', 'ช้า'], used: false },
  { words: ['เบา', 'หนัก'], used: false },
  { words: ['แข็งแรง', 'อ่อนแอ'], used: false },
  { words: ['สิ่งที่แข็ง', 'สิ่งที่อ่อน'], used: false },
  { words: ['สุข', 'ทุกข์'], used: false },
  { words: ['ฉลาด', 'โง่'], used: false },
  { words: ['เสียงดัง', 'เงียบ'], used: false },
  { words: ['มืด', 'สว่าง'], used: false },
  { words: ['มีราคา', 'ราคาถูก'], used: false },
  { words: ['สมัยใหม่', 'โบราณ'], used: false },
  { words: ['อันตราย', 'ปลอดภัย'], used: false },
  { words: ['ขนน้อย', 'ขนปุย'], used: false },
  { words: ['เป็นธรรมชาติ', 'สร้างโดยมนุษย์'], used: false },
  { words: ['ทำได้ง่าย', 'ทำได้ยาก'], used: false },
  { words: ['ตลก', 'จริงจัง'], used: false },
  { words: ['สะอาด', 'สกปรก'], used: false },
  { words: ['กล้า', 'ขี้ขลาด'], used: false },
  { words: ['Green flag', 'Red flag'], used: false },
  { words: ['คำแนะนำที่ดี', 'คำแนะนำที่แย่'], used: false },
  { words: ['มีเหตุผล', 'ใช้อารมณ์'], used: false },
  { words: ['ว่างเปล่า', 'เต็ม'], used: false },
  { words: ['คำบอกเลิกที่ดี', 'คำบอกเลิกที่แย่'], used: false },
  { words: ['Introvert', 'Extrovert'], used: false },
  { words: ['แห้ง', 'เปียก'], used: false },
  { words: ['เป็นมิตร', 'เป็นศัตรู'], used: false },
  { words: ['เด็ก', 'แก่'], used: false },
  { words: ['เปิดเผย', 'ปิดบัง'], used: false },
  { words: ['ชอบ', 'ไม่ชอบ'], used: false },
  { words: ['กลิ่นเหม็น', 'กลิ่นหอม'], used: false },
  { words: ['จริงจัง', 'เล่นๆ'], used: false },
  { words: ['ซีรีส์ที่เจ๋ง','ซีรีส์ที่กาก'], used: false},
  { words: ['สิ่งที่หาง่าย', 'สิ่งที่หายาก'], used: false},
  { words: ['บุคคลทรงคุณค่า', 'บุคคลทรงคุณไสย'], used: false},
  { words: ['รู้สึกดี', 'รู้สึกแย่'], used: false},
  { words: ['สูง', 'ต่ำ'], used: false},
  { words: ['รู้สึกดี', 'รู้สึกแย่'], used: false},
  { words: ['อร่อย', 'ไม่อร่อย'], used: false },
  { words: ['เทคโนโลยีมีประโยชน์', 'เทคโนโลยีมีทำไม'], used: false},
  { words: ['หนังที่โรแมนติก', 'หนังที่ไม่โรแมนติก'], used: false},
  { words: ['นิสัยที่จำเป็น', 'นิสัยที่ไม่จำเป็น'], used: false},
  { words: ['สัตว์เลี้ยงที่ดี', 'สัตว์เลี้ยงที่แย่'], used: false},
  { words: ['คลาสที่น่าเรียน', 'คลาสที่ไม่น่าเรียน'], used: false},
  { words: ['สิ่งที่ไม่อยากเสีย', 'สิ่งที่ต้องการทิ้ง'], used: false},
  { words: ['Superhero ที่น่าประทับใจ', 'Superhero ที่น่าลืม ๆ ไปซะ'], used: false},
  { words: ['สิ่งที่ขี่เหร่', 'สิ่งที่งดงาม'], used: false},
  { words: ['ไม่ยืดหยุ่น', 'ยืดหยุ่น'], used: false},
  { words: ['สิ่งประดิษฐ์มีประโยชน์', 'สิ่งประดิษฐ์มีทำไม'], used: false},
  { words: ['คุณภาพสูง', 'คุณภาพต่ำ'], used: false},
  { words: ['สิ่งที่ไม่ควรทำ', 'สิ่งที่ควรทำ'], used: false},
  { words: ['Topping pizza ที่ควร', 'Topping pizza ที่ไม่ควร'], used: false},
  { words: ['ต้องการโชคมาก', 'ต้องการทักษะมาก'], used: false},
  { words: ['อวัยวะมีประโยชน์', 'อวัยวะมีทำไม'], used: false},
  { words: ['กิจกรรมน่าเบื่อ', 'กิจกรรมน่าสนุก'], used: false},
  { words: ['พลังวิเศษที่มีประโยชน์', 'พลังวิเศษที่ไร้ประโยชน์'], used: false},
  { words: ['ชั่วคราว', 'ถาวร'], used: false},
  { words: ['ตรงเวลาเสมอ', 'สายเสมอ'], used: false},
  { words: ['เสรีนิยม', 'อนุรักษ์นิยม'], used: false},
  { words: ['สถานที่เงียบ', 'สถานที่เสียงดัง'], used: false},
  { words: ['สิ่งที่ไม่ควรมีติดตัว', 'สิ่งที่ควรพกติดตัว'], used: false},
  { words: ['ตัวละครที่แข็งแกร่ง', 'ตัวละครที่อ่อนแอ'], used: false},
  { words: ['อาหารที่แห้ง', 'อาหารที่เปียก'], used: false},
  { words: ['สถานที่ท่องเที่ยวที่น่าไป', 'สถานที่ท่องเที่ยวที่น่าเลี่ยง'], used: false },
  { words: ['อาหารเช้าที่ดี', 'อาหารเช้าที่แย่'], used: false },
  { words: ['กีฬาที่ใช้แรงมาก', 'กีฬาที่ใช้แรงน้อย'], used: false },
  { words: ['เรื่องที่ทำให้แฟนโกรธ', 'เรื่องที่ทำให้แฟนชอบ'], used: false },
  { words: ['อาชีพที่ได้เงินมาก', 'อาชีพที่ได้เงินน้อย'], used: false },
  { words: ['เพื่อนบ้านที่ดี', 'เพื่อนบ้านที่แย่'], used: false },
  { words: ['สิ่งที่ทำให้อายมาก', 'สิ่งที่ไม่อายเลย'], used: false },
  { words: ['วันที่ดีที่สุดของสัปดาห์', 'วันที่แย่ที่สุดของสัปดาห์'], used: false },
  { words: ['ข่าวดี', 'ข่าวร้าย'], used: false },
  { words: ['เรื่องผีที่น่ากลัว', 'เรื่องผีที่ไม่น่ากลัว'], used: false },
  { words: ['ความฝันที่เป็นไปได้', 'ความฝันที่เป็นไปไม่ได้'], used: false },
  { words: ['ของที่ซื้อแล้วคุ้ม', 'ของที่ซื้อแล้วเสียดาย'], used: false },
  { words: ['สิ่งที่ควรเรียนในโรงเรียน', 'สิ่งที่ไม่ควรเรียนในโรงเรียน'], used: false },
  { words: ['งานบ้านที่น่าทำ', 'งานบ้านที่น่าเบื่อ'], used: false },
  { words: ['มารยาทที่ควรมี', 'มารยาทที่ไม่จำเป็น'], used: false },
  { words: ['เรื่องที่พูดในที่ประชุมได้', 'เรื่องที่ไม่ควรพูดในที่ประชุม'], used: false },
];
